name: terraform

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  id-token: write     # needed for OIDC
  contents: read
  pull-requests: write

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  AWS_REGION: me-central-1
  TF_VERSION: "1.6.6"
  WORKING_DIR: terraform
  VAR_FILE: environments/dev.tfvars

jobs:
  apply:
    name: terraform apply (main)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: dev   # enables GitHub Environment protections/approvals if you configure them

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-terraform-apply

      - name: Terraform Init
        working-directory: ${{ env.WORKING_DIR }}
        run: terraform init -no-color

      - name: Terraform Apply
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          terraform apply -no-color -auto-approve -var-file="${{ env.VAR_FILE }}"
